import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          defer src="http://localhost:3000/script.js" data-website-id="df18a018-08c5-4242-8756-dd2272e1afac"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
