import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          defer src="https://analytics.bkn.go.id/script.js" data-website-id="c54e0cf8-e804-4618-9487-e98572cfe66c"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
